site_name: My Docs

theme:
  name: material
  palette:
    primary: black
  icon:
    repo: fontawesome/brands/git-alt

repo_url: https://github.com/VladKovalevv/ITMO_ICT_WebDevelopment_2023-2024

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - "№1: Сокеты":
      - lab1/index.md
      - lab1/task1.md
      - lab1/task2.md
      - lab1/task3.md
      - lab1/task4.md
      - lab1/task5.md
  - "№2:Доска домашних заданий":
      - lab2/index.md
