# Generated by Django 4.2.6 on 2023-10-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0004_rename_subject_homework_subject_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='homeworkgrade',
            old_name='homework_submission_id',
            new_name='homework_submission',
        ),
        migrations.RenameField(
            model_name='homeworksubmission',
            old_name='homework_id',
            new_name='homework',
        ),
        migrations.RenameField(
            model_name='homeworksubmission',
            old_name='student_id',
            new_name='student',
        ),
    ]
